title: "Dozin Company"
description: "Dozin Company is a tech company specializing in AI & R&D."
url: "https://www.dozin.company"

social:
  linkedin: "https://www.linkedin.com/company/dozin-company"
  twitter: "https://twitter.com/dozin_company"

search_url: "https://www.dozin.company/search?q="